DATABASE_URL: jdbc:postgresql://localhost:5432/CRUDfood
DATABASE_USER: postgres
DATABASE_PASSWORD: postgres

LOCAL_DATABASE_URL: jdbc:h2:mem:CRUDfood;DB_CLOSE_DELAY=-1
LOCAL_DATABASE_USER: sa
LOCAL_DATABASE_PASSWORD:
