DATABASE_URL: jdbc:postgresql://localhost:5432/CRUDfood
DATABASE_USER: postgres
DATABASE_PASSWORD: postgres

LOCAL_DATABASE_URL: jdbc:h2:mem:CRUDfood;DB_CLOSE_DELAY=-1
LOCAL_DATABASE_USER: sa
LOCAL_DATABASE_PASSWORD:

APP_DATABASE_PROVIDER: local
APP_CUSTOMER_REPOSITORY_IMPL: jpa
APP_FOOD_REPOSITORY_IMPL: jpa
APP_CUSTOMER_SERVICE_IMPL: default
APP_FOOD_SERVICE_IMPL: default
